version: '3'
services:
    web:
        build: .
        container_name: axentom-web
        ports:
            - 5002:5000
        volumes:
            - ./data/animals.json:/animals.json
    redis:
        image: redis:latest
        container_name: axentom-redis
        ports:
            - 6382:6379
        volumes:
            - ./config/redis.conf:/redis.conf
            - ./data/animals.json:/animals.json
        command: [ "redis-server", "/redis.conf" ]

