version: '3'
services:
    flask:
        image: axentom/axentom_web:midtermProjectWebApp
        container_name: axentom-flask
        command: "api.py"
        ports:
            - 5002:5000
        #volumes:
            #- ../data/data.json:/data.json
    redis:
        image: redis:latest
        container_name: axentom-redis
        ports:
            - 6382:6379
        volumes:
            - ../data/redis.conf:/redis.conf
            #- ../data/data.json:/data.json
        command: [ "redis-server", "/redis.conf" ]
    worker:
        image: axentom/axentom_web:finalProjectWorker
        container_name: axentom-worker
        command: "worker.py"
