---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: axentom-prod-redis-pvc
  labels:
    username: axentom
    env: prod
    app: axentom-prod-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
