---
apiVersion: v1
kind: Service
metadata:
  name: axentom-prod-redis-service
  labels:
    username: axentom
    env: prod
    app: axentom-prod-redis
spec:
  type: ClusterIP
  selector:
    app: axentom-prod-redis
  ports:
  - name: axentom-prod-redis
    port: 6379
    targetPort: 6379
