---
apiVersion: v1
kind: Service
metadata:
  name: axentom-test-redis-service
  labels:
    username: axentom
    env: test
    app: axentom-test-redis
spec:
  type: ClusterIP
  selector:
    app: axentom-test-redis
  ports:
  - name: axentom-test-redis
    port: 6379
    targetPort: 6379
