---
apiVersion: v1
kind: Service
metadata:
  name: axentom-test-flask-service
  labels:
    username: axentom
    env: test
    app: axentom-test-flask
spec:
  type: ClusterIP
  selector:
    app: axentom-test-flask
  ports:
  - name: axentom-test-flask
    port: 5000
    targetPort: 5000
