---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwk5-deployment
  labels:
    app: hwk5-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hwk5-app
  template:
    metadata:
      labels:
        app: hwk5-app
    spec:
      containers:
        - name: hwk5
          image: ubuntu:18.04
          env:
          - name: NAME
            value: "Thomas"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command: ['sh', '-c', 'echo "Hello, $NAME from IP $POD_IP" && sleep 3600']
